version: "2"
linters:
  enable:
    - staticcheck
    - errcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1005"
        - "-ST1000"
run:
  allow-parallel-runners: true
